version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  Build-and-Test:
    docker:
      - image: node:latest
    steps:
      - checkout
      - run: mkdir reports
      - run:
          name: "Install Dependencies"
          command: "npm install"
      - run:
          name: "Run Tests"
          command: "npm run test"
      - run:
          name: "Wrapping Test Result"
          command: "tar -cvf artifact.tar reports/"
      - store_artifacts:
          path: artifact.tar
      - codecov/upload:
          file: cover
          token: ${CODECOV_TOKEN}

workflows:
  API-Testing-Workflow:
    jobs:
      - Build-and-Test