version: 2.1
jobs:
  Build-and-Test:
    docker:
      - image: pridecontrol/mocha-api:v1
        auth:
          username: $USERNAME
          password: $PASSWORD
    steps:
      - checkout
      # - run: mkdir reports
      # - run:
      #     name: "Install Dependencies"
      #     command: "npm install"
      - run:
          name: "Prepare Test"
          command: |
            cp -r ./api /app/
            cp -r ./connector /app/
            cp -r ./helpers /app/
            cp -r ./testcases /app/
      - run:
          name: "Run Tests"
          command: |
            cd /app/
            npm run test
      - run:
          name: "Wrapping Test Result"
          command: "tar -cvf artifact.tar reports/"
      - store_artifacts:
          path: artifact.tar
      # - run:
      #     name: "Upload Code Coverage Result"
      #     command: |
      #       npm run coverage
      #       curl -Os https://uploader.codecov.io/latest/linux/codecov 
      #       chmod +x codecov 
      #       ./codecov --token=${CODECOV_TOKEN}

workflows:
  API-Testing-Workflow:
    jobs:
      - Build-and-Test